import type { Field, Tool, ToolFamilyId, ToolEngine, Result } from './types';
const field = (
  key: string,
  label: string,
  value: string,
  type: Field['type'] = 'text',
  help?: string,
): Field => ({
  key,
  label,
  default: value,
  type,
  help,
  adjustment:
    type === 'number'
      ? { kind: 'number' }
      : type === 'time'
        ? { kind: 'time' }
        : type === 'date'
          ? { kind: 'date' }
          : /^[-+]?\d+:\d{2}/.test(value)
            ? { kind: 'auto' }
            : undefined,
});
const numeric = (
  key: string,
  label: string,
  value: string,
  min?: number,
  max = 1e12,
  step = 1,
  integer = false,
): Field => ({
  ...field(key, label, value, 'number'),
  min: min === undefined ? undefined : String(min),
  max: String(max),
  step: String(step),
  adjustment: { kind: 'number', min, max, step, integer },
});
const select = (
  key: string,
  label: string,
  value: string,
  options: [string, string][],
): Field => ({ key, label, default: value, type: 'select', options });
const nextDay = select('overnight', 'End day', 'no', [
  ['no', 'Same day'],
  ['yes', 'Next day'],
]);
const choice = select('choice', 'Repeated clock time', 'reject', [
  ['reject', 'Ask me if the time occurs twice'],
  ['earlier', 'Earlier occurrence'],
  ['later', 'Later occurrence'],
]);
const units: [string, string][] = [
  'seconds',
  'minutes',
  'hours',
  'days',
  'weeks',
].map((x) => [x, x[0].toUpperCase() + x.slice(1)]);
const definition = (
  id: string,
  name: string,
  family: ToolFamilyId,
  engine: ToolEngine,
  description: string,
  intro: string,
  fields: Field[],
  example: string,
  convention: string,
  related: string[],
  value: string,
  detail = '',
  rows?: Result['rows'],
): Tool => ({
  id,
  name,
  family,
  engine,
  description,
  intro,
  fields,
  example,
  convention,
  related,
  defaultResult: { value, detail, rows },
});

export const tools: Tool[] = [
  definition(
    'timer',
    'Online timer',
    'timers',
    null,
    'Start a free online timer in seconds, or count down to a clock time in any time zone.',
    'Set a duration for cooking, study, or a short break. Switch to Until to finish at a particular clock time, including a time in another part of the world. Keep this tab available for the alarm.',
    [],
    'Choose 5 minutes and press Start. For a deadline, choose Until, enter 17:00, and check whether the preview says Today or Tomorrow.',
    'Duration timers can pause. Deadlines keep counting toward their fixed instant. A closed or suspended browser cannot guarantee an alarm.',
    ['stopwatch', 'interval-timer', 'countdown'],
    '05:00',
  ),
  definition(
    'countdown',
    'Countdown to a date',
    'timers',
    null,
    'Create an editable countdown to an event with an exact date, time, and time zone.',
    'Count down to an appointment, launch, birthday, or trip. Give the event a name and choose its date and time zone. Shared links preserve the exact instant so viewers in different zones count down to the same event.',
    [],
    'For an event at 09:00 in Tokyo, select Asia/Tokyo and the event date. The local-time preview shows when it happens where you are.',
    'The event is an absolute deadline. Daylight-saving gaps are rejected; repeated clock times require an earlier or later choice.',
    ['timer', 'date-difference', 'time-zone'],
    'Choose your event',
  ),
  definition(
    'stopwatch',
    'Stopwatch with laps',
    'timers',
    null,
    'Measure elapsed time with a free stopwatch, pause controls, and split laps.',
    'Measure a task, a practice session, or a race. Record laps without stopping the overall clock. Each lap shows the split since the previous lap and the total elapsed time.',
    [],
    'Start the stopwatch, record a lap at 30 seconds, then another at 50 seconds. The second split is 20 seconds.',
    'Elapsed time is derived from timestamps. Refresh restores the stopwatch in this tab; changes to your device clock may affect timing.',
    ['timer', 'running-pace', 'sum-durations'],
    '00:00.00',
  ),
  definition(
    'interval-timer',
    'Work & rest interval timer',
    'timers',
    null,
    'Repeat work and rest intervals for exercise, focus sessions, or practice.',
    'Set a work period, a rest period, and the number of rounds. The timer advances automatically, announces phase changes when sound is available, and finishes immediately after the final work period.',
    [
      numeric('work', 'Work seconds', '30', 1, 86400, 1, true),
      numeric('rest', 'Rest seconds', '10', 0, 86400, 1, true),
      numeric('rounds', 'Rounds', '8', 1, 1000, 1, true),
    ],
    'Eight rounds of 30 seconds work and 10 seconds rest take 5 minutes 10 seconds. There is no rest period after the last round.',
    'Pause stops elapsed session time. A delayed browser catches up to the current phase without replaying every missed alarm.',
    ['timer', 'stopwatch', 'time-calculator'],
    '05:10',
  ),
  definition(
    'time-calculator',
    'Time calculator',
    'time-math',
    'work',
    'Add, subtract, multiply, or divide hours, minutes, and seconds without converting them by hand.',
    'Combine durations, find a difference, or scale a task estimate. Use hours:minutes:seconds for durations and a plain number for multiplication or division. Negative results are supported.',
    [
      field('a', 'First duration', '1:30:00'),
      select('operation', 'Operation', 'add', [
        ['add', 'Add'],
        ['subtract', 'Subtract'],
        ['multiply', 'Multiply'],
        ['divide', 'Divide'],
      ]),
      field('b', 'Second duration or factor', '0:45:00'),
    ],
    '1:30:00 + 0:45:00 = 2:15:00. To divide 1:30:00 into three equal parts, choose Divide and enter 3.',
    'These are fixed durations, not dates. Intermediate calculations use decimal arithmetic; displayed results are rounded to milliseconds.',
    ['sum-durations', 'decimal-hours', 'start-finish'],
    '2:15:00',
    '8100 seconds · 2.25 hours',
  ),
  definition(
    'sum-durations',
    'Sum durations',
    'time-math',
    'work',
    'Add a list of times to find a playlist, agenda, or total task duration.',
    'Enter one duration per line to total a playlist, video sequence, or schedule. Blank lines are ignored. Hours can exceed 24, so long projects do not wrap back to zero.',
    [
      field(
        'list',
        'Durations, one per line',
        '0:30:00\n1:15:00\n0:45:00',
        'textarea',
        'Use H:MM or H:MM:SS. Up to 1,000 lines.',
      ),
    ],
    '0:30:00, 1:15:00, and 0:45:00 total 2:30:00, or 2.5 hours.',
    'Negative durations subtract from the total. Only duration values are accepted; leave task names out of the list.',
    ['time-calculator', 'playback-speed', 'decimal-hours'],
    '2:30:00',
    '3 durations · 2.5 hours',
  ),
  definition(
    'time-between',
    'Time between clock readings',
    'time-math',
    'work',
    'Calculate the hours and minutes between two clock times, including overnight periods.',
    'Find how long a shift, class, or activity lasts from its start and end clock readings. Select Next day when the end belongs to the following day.',
    [
      field('start', 'Start time', '09:00', 'time'),
      field('end', 'End time', '17:30', 'time'),
      nextDay,
    ],
    '09:00 to 17:30 is 8 hours 30 minutes. 22:00 to 06:00 on the next day is 8 hours.',
    'This is clock arithmetic over at most 24 hours. Use the time-zone converter for real instants across a daylight-saving transition.',
    ['work-hours', 'start-finish', 'time-zone'],
    '8:30:00',
    '510 minutes · fixed clock arithmetic',
  ),
  definition(
    'work-hours',
    'Work hours calculator',
    'work',
    'work',
    'Calculate working time after unpaid breaks for a daytime or overnight shift.',
    'Enter your shift times and the total number of unpaid break minutes. The result shows both a clock duration and decimal hours, making it easy to copy into a time record.',
    [
      field('start', 'Clock in', '09:00', 'time'),
      field('end', 'Clock out', '17:30', 'time'),
      nextDay,
      numeric('breaks', 'Unpaid break minutes', '30', 0),
    ],
    '09:00–17:30 with a 30-minute break gives 8:00:00, or 8 decimal hours.',
    'Breaks cannot exceed the shift. This tool measures hours and does not apply overtime, tax, or payroll rules.',
    ['timesheet', 'decimal-hours', 'time-between'],
    '8:00:00',
    '8 paid hours · 30 minutes of breaks',
  ),
  definition(
    'timesheet',
    'Weekly timesheet',
    'work',
    'work',
    'Total a weekly timesheet with daily breaks, overnight shifts, and CSV export.',
    'Fill in the days you worked and leave both times blank for a day off. Review daily totals and export a CSV with decimal hours for your own records.',
    Array.from({ length: 7 }, (_, i) => [
      field(`start${i}`, 'Start', i < 5 ? '09:00' : '', 'time'),
      field(`end${i}`, 'End', i < 5 ? '17:00' : '', 'time'),
      numeric(`break${i}`, 'Break minutes', '30', 0),
      select(`overnight${i}`, 'End day', 'no', [
        ['no', 'Same day'],
        ['yes', 'Next day'],
      ]),
    ]).flat(),
    'Five 09:00–17:00 shifts with a 30-minute unpaid break each total 37.5 hours.',
    'Hours are calculated per shift without intermediate rounding. CSV values are plain data. No overtime, holiday pay, or wage calculation is included.',
    ['work-hours', 'decimal-hours', 'business-days'],
    '37.5 hours',
    '37:30:00 total',
  ),
  definition(
    'decimal-hours',
    'Decimal hours converter',
    'work',
    'work',
    'Convert hours and minutes to decimal hours, or decimal hours back to clock time.',
    'Switch between a clock duration and the decimal form often used in time records. A quarter hour is 0.25 hours, not 0.15 hours.',
    [
      select('direction', 'Convert', 'to-decimal', [
        ['to-decimal', 'Duration → decimal hours'],
        ['to-duration', 'Decimal hours → duration'],
      ]),
      field('amount', 'Duration or decimal hours', '1:30:00'),
    ],
    '1:30:00 = 1.5 hours. In the other direction, 2.75 hours = 2:45:00.',
    'Decimal output is rounded to six places. Duration output is rounded to milliseconds; a copied displayed value has the same precision.',
    ['work-hours', 'time-units', 'time-calculator'],
    '1.5 hours',
    '90 minutes',
  ),
  definition(
    'time-units',
    'Time unit converter',
    'time-math',
    'work',
    'Convert seconds, minutes, hours, fixed days, and weeks.',
    'Convert a quantity between common time units. This is useful for estimates, media lengths, and tasks where a day means exactly 24 hours.',
    [
      numeric('amount', 'Amount', '90'),
      select('from', 'From', 'minutes', units),
      select('to', 'To', 'hours', units),
    ],
    '90 minutes = 1.5 hours. 2 fixed days = 48 hours = 172,800 seconds.',
    'Months and years are omitted because their length depends on the calendar. For calendar changes, use Add or subtract dates.',
    ['decimal-hours', 'add-dates', 'frames-duration'],
    '1.5 hours',
    'Fixed units: one day = 24 hours; one week = 7 days.',
  ),
  definition(
    'start-finish',
    'Start / finish time calculator',
    'time-math',
    'work',
    'Find a finish time from a duration, or work backwards to a starting time.',
    'Plan when to start a task or when it will finish. The day offset makes it clear when a calculation crosses midnight, including tasks longer than one day.',
    [
      select('direction', 'Find', 'finish', [
        ['finish', 'Finish time'],
        ['start', 'Start time'],
      ]),
      field('time', 'Known clock time', '09:00', 'time'),
      field('duration', 'Task duration', '1:30:00'),
    ],
    'A 1:30:00 task starting at 09:00 finishes at 10:30. To finish at 09:00, start at 07:30.',
    'The result uses fixed clock arithmetic. It does not apply a time zone or daylight-saving changes.',
    ['timer', 'time-between', 'time-calculator'],
    '10:30:00',
    'Same day',
  ),
  definition(
    'date-difference',
    'Date difference calculator',
    'dates',
    'calendar',
    'Find the number of calendar days, months, and years between two dates.',
    'Compare dates for a project, trip, or milestone. The main result gives signed calendar days; the second line describes the same interval in calendar years, months, and days.',
    [
      field('start', 'Start date', '2026-01-01', 'date'),
      field('end', 'End date', '2027-01-01', 'date'),
    ],
    'January 1, 2026 to January 1, 2027 is 365 days, or 1 calendar year.',
    'The start is included and the end is excluded. These are calendar days, not a count of 24-hour periods between zoned instants.',
    ['add-dates', 'business-days', 'countdown'],
    '365 days',
    '1 years, 0 months, 0 days · end date excluded',
  ),
  definition(
    'add-dates',
    'Add or subtract dates',
    'dates',
    'calendar',
    'Move a calendar date forward or back by days, months, and years.',
    'Find a date after a project interval or work backwards from a milestone. Calendar months keep the day number when possible and use the last valid day when necessary.',
    [
      field('date', 'Starting date', '2026-01-31', 'date'),
      select('operation', 'Direction', 'add', [
        ['add', 'Add'],
        ['subtract', 'Subtract'],
      ]),
      numeric('years', 'Years', '0', undefined, 10000, 1, true),
      numeric('months', 'Months', '1', undefined, 120000, 1, true),
      numeric('days', 'Days', '0', undefined, 3660000, 1, true),
    ],
    'January 31, 2026 plus one month becomes February 28, 2026. January 31, 2024 plus one month becomes February 29.',
    'Years and months are applied together, then days. Month-end clamping is explicit; adding and subtracting a month may not return the original date.',
    ['date-difference', 'weekday', 'business-days'],
    '2026-02-28',
    'Saturday · month-end dates are clamped to the last valid day',
  ),
  definition(
    'business-days',
    'Business days calculator',
    'dates',
    'calendar',
    'Count working days using your own working week and excluded dates.',
    'Choose the weekdays that count as working days, then enter any holidays or other excluded dates. The tool works for a standard Monday–Friday week or a custom schedule.',
    [
      field('start', 'Start date', '2026-09-28', 'date'),
      field('end', 'End date', '2026-10-05', 'date'),
      field(
        'week',
        'Working weekdays',
        '1,2,3,4,5',
        'text',
        'Monday = 1 through Sunday = 7. Separate numbers with commas.',
      ),
      field(
        'excluded',
        'Excluded dates',
        '',
        'textarea',
        'YYYY-MM-DD, separated by newlines or commas.',
      ),
      select('inclusive', 'Include end date', 'no', [
        ['no', 'No'],
        ['yes', 'Yes'],
      ]),
    ],
    'September 28 to October 5, 2026 has 5 Monday–Friday working days with the end excluded. Excluding September 30 reduces the count to 4.',
    'No country holiday database is maintained. The start date counts if eligible; choose whether to count the end date.',
    ['date-difference', 'timesheet', 'weekday'],
    '5 business days',
    'Start included; end excluded.',
  ),
  definition(
    'weekday',
    'Weekday finder',
    'dates',
    'calendar',
    'Find which day of the week a date falls on, with its day of the year.',
    'Check the weekday of a birthday, appointment, or historical date. The result also shows its position within the year so you can check a schedule quickly.',
    [field('date', 'Date', '2026-09-29', 'date')],
    'September 29, 2026 is a Tuesday and the 272nd day of a 365-day year.',
    'Calculations use the ISO Gregorian calendar for years 0001–9999; historical local calendar adoption is not modeled.',
    ['iso-week', 'add-dates', 'date-difference'],
    'Tuesday',
    '2026-09-29 · day 272 of 365',
  ),
  definition(
    'iso-week',
    'ISO week number',
    'dates',
    'calendar',
    'Find the ISO week number, week year, and weekday for a date.',
    'Look up the ISO week used in production schedules and weekly planning. The ISO week year can differ from the calendar year around New Year.',
    [field('date', 'Date', '2021-01-01', 'date')],
    'January 1, 2021 belongs to 2020-W53. January 4, 2021 begins 2021-W01.',
    'ISO weeks start on Monday. Week 1 contains January 4, and the week year is shown explicitly.',
    ['weekday', 'timesheet', 'date-difference'],
    '2020-W53',
    'ISO weekday 5 (Friday). Week 1 contains January 4.',
  ),
  definition(
    'time-zone',
    'Time zone converter',
    'time-zones',
    'calendar',
    'Convert a dated clock time between cities, including daylight-saving changes.',
    'Choose a date, clock time, source zone, and destination zone. Using the date makes seasonal offsets explicit. Search by city or pick a fixed abbreviation such as PST.',
    [
      field('date', 'Date in source zone', '2026-01-15', 'date'),
      field('time', 'Clock time', '09:00', 'time'),
      field('from', 'From time zone', 'America/New_York', 'zone'),
      field('to', 'To time zone', 'Europe/London', 'zone'),
      choice,
    ],
    '09:00 in New York on January 15, 2026 is 14:00 in London on the same date.',
    'PST is fixed UTC−08:00; Los Angeles uses seasonal Pacific Time. Missing times are rejected, and repeated times require a choice.',
    ['meeting-planner', 'timer', 'countdown'],
    '2026-01-15 14:00:00 (Europe/London, UTC+00:00)',
    'Same instant as 09:00 in New York',
  ),
  definition(
    'meeting-planner',
    'Meeting time overlap planner',
    'time-zones',
    'calendar',
    'Find half-hour meeting slots within working hours across two to four time zones.',
    'Compare the local working day in up to four cities. Pick the planning date in the first zone and a common range of local working hours. Each result is a full 30-minute slot available everywhere.',
    [
      field('date', 'Date in first zone', '2026-01-15', 'date'),
      field('zone1', 'First time zone', 'Europe/London', 'zone'),
      field('zone2', 'Second time zone', 'America/New_York', 'zone'),
      field('zone3', 'Third time zone (optional)', '', 'zone'),
      field('zone4', 'Fourth time zone (optional)', '', 'zone'),
      numeric('start', 'Local work begins (hour)', '9', 0, 23, 1, true),
      numeric('end', 'Local work ends (hour)', '17', 1, 24, 1, true),
    ],
    'London and New York, 09:00–17:00 on January 15, 2026: shared availability is 14:00–17:00 London, or 09:00–12:00 New York.',
    'Slots step in 30-minute elapsed increments, with local dates shown for every zone. Working hours apply daily; weekends and holidays are not filtered.',
    ['time-zone', 'business-days', 'countdown'],
    '6 half-hour meeting slots',
    '14:00–17:00 London · 09:00–12:00 New York',
  ),
  definition(
    'playback-speed',
    'Playback speed calculator',
    'rates-media',
    'rates',
    'Calculate video or audiobook duration at any playback speed. See how much watching or listening time you save or add, with worked examples.',
    'Enter the original media length and the playback multiplier. The result is the time you will spend listening or watching, assuming continuous playback without pauses.',
    [
      field('duration', 'Original duration', '1:00:00'),
      {
        ...numeric('speed', 'Playback multiplier', '1.5', 0.01, 100, 0.1),
        step: 'any',
        presets: [
          ['0.75', '0.75×'],
          ['1', '1×'],
          ['1.25', '1.25×'],
          ['1.5', '1.5×'],
          ['1.75', '1.75×'],
          ['2', '2×'],
        ],
      },
    ],
    'A one-hour recording at 1.5× speed takes 40 minutes. At 0.75× speed, it takes 1 hour 20 minutes.',
    'Duration is divided by speed. Seeking, ads, and pauses are not included.',
    ['sum-durations', 'frames-duration', 'speech-duration'],
    '0:40:00',
    '1.5× playback · 40 minutes',
    [['Time saved', '0:20:00']],
  ),
  definition(
    'speech-duration',
    'Speech duration estimate',
    'rates-media',
    'rates',
    'Estimate speaking time from a word count and an adjustable delivery rate.',
    'Enter your script word count, expected words per minute, and extra time for pauses. Adjust the speaking rate to match your delivery and confirm with a rehearsal.',
    [
      numeric('words', 'Word count', '600', 0),
      numeric('wpm', 'Words per minute', '130', 1, 1000),
      numeric('pause', 'Extra pauses (seconds)', '30', 0),
    ],
    '600 words at 120 words/minute take 5 minutes. With 30 seconds of extra pauses, allow 5:30.',
    'Speaking rate is an assumption, not a prediction. Audience response, pronunciation, and slide transitions can change the real duration.',
    ['timer', 'sum-durations', 'start-finish'],
    '0:05:06.923',
    'Estimate at 130 words/minute plus 30 seconds of pauses.',
  ),
  definition(
    'running-pace',
    'Running pace calculator',
    'rates-media',
    'rates',
    'Calculate average running pace per kilometre or mile and average speed.',
    'Enter your distance and finishing time to find an average pace. Select kilometres or miles so the result uses the same unit as your run.',
    [
      numeric('distance', 'Distance', '5', 0.001, 1e12, 0.1),
      select('unit', 'Distance unit', 'km', [
        ['km', 'Kilometres'],
        ['mi', 'Miles'],
      ]),
      field('duration', 'Finishing time', '0:25:00'),
    ],
    '5 km in 25 minutes is a pace of 5:00 per kilometre and an average speed of 12 km/h.',
    'Pace includes the entire entered time, including stops. It does not model elevation, splits, or moving time separately.',
    ['stopwatch', 'interval-timer', 'time-units'],
    '0:05:00 / km',
    '12 km/h · average pace over the whole distance',
  ),
  definition(
    'render-time',
    'Render time calculator',
    'rates-media',
    'rates',
    'Estimate animation render time from frame count, seconds per frame, parallel workers, and overhead. See worked examples and planning limits.',
    'Use a representative per-frame render time to estimate completion. Enter equally capable workers and an overhead allowance for scheduling, transfers, or other work.',
    [
      numeric('frames', 'Frame count', '240', 1, 1e9, 1, true),
      numeric('seconds', 'Seconds per frame', '30', 0.001, 1e12, 0.1),
      numeric('workers', 'Parallel workers', '4', 1, 10000, 1, true),
      numeric('overhead', 'Overhead percent', '10', 0, 1000),
    ],
    '240 frames at 30 seconds each on 4 equal workers take 30 minutes ideally, or 33 minutes with 10% overhead.',
    'Whole frame batches are rounded up. Actual speed depends on frame complexity, hardware, memory, and distribution; this is not a cost quote.',
    ['frames-duration', 'time-calculator', 'start-finish'],
    '0:33:00',
    '60 frame batches · equal workers, ideal distribution, 10% overhead',
  ),
  definition(
    'frames-duration',
    'Frames to seconds calculator',
    'rates-media',
    'rates',
    'Convert frames to seconds, minutes, and hours at your chosen FPS. Compare common frame rates, use custom values, and see worked examples.',
    'Find the running length of an animation, clip, or sequence. Enter the actual frames-per-second value rather than a timecode label. Fractional frame rates are supported.',
    [
      numeric('frames', 'Frame count', '2400', 0, 1e12, 1, true),
      {
        ...numeric('fps', 'Frames per second', '24', 0.001, 100000, 0.1),
        step: 'any',
        presets: [
          ['23.976', '23.976'],
          ['24', '24'],
          ['25', '25'],
          ['29.97', '29.97'],
          ['30', '30'],
          ['50', '50'],
          ['59.94', '59.94'],
          ['60', '60'],
        ],
      },
    ],
    '2,400 frames at 24 fps last 100 seconds, or 1:40. At 30 fps they last 80 seconds.',
    'This converts elapsed frames to seconds. It does not generate SMPTE timecode or implement drop-frame numbering.',
    ['render-time', 'playback-speed', 'time-units'],
    '0:01:40',
    '100 seconds at 24 fps. No SMPTE or drop-frame timecode.',
  ),
];
export const toolPath = (id: string) => (id === 'timer' ? '/' : `/${id}/`);
export const getTool = (id: string) => tools.find((t) => t.id === id)!;
